server:
  port: 5050

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/db_lpyx?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    static-path-pattern: /static/** # 静态资源仅匹配 /static/ 开头的路径


mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  config-locations: classpath:mybatis-config.xml

# 自定义配置
lpyx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode


  minio:
    endpointUrl: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: lpyx-bucket